const data = {
  deals: [
    {
      id: "deal01",
      name: "Ranch Box",
      desc: "1 Medium Cheese Stuffed Crust pizza + 1 Medium Beef & Cheddar Stuffed Crust pizza + Potato wedges + Salad + Pepsi 1L.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/deals-pp_01.jpg",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/deal-01.jpg",
      price: 245,
    },
    {
      id: "deal02",
      name: "Ranch Box",
      desc: "1 Medium Cheese Stuffed Crust pizza + 1 Medium Beef & Cheddar Stuffed Crust pizza + Potato wedges + Salad + Pepsi 1L.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/deals-pp_02.jpg",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/deal-02.jpg",
      price: 240,
    },
    {
      id: "deal03",
      name: "Ranch Box",
      desc: "1 Medium Cheese Stuffed Crust pizza + 1 Medium Beef & Cheddar Stuffed Crust pizza + Potato wedges + Salad + Pepsi 1L.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/deals-pp_03.jpg",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/deal-03.jpg",
      price: 323,
    },
    {
      id: "deal04",
      name: "Ranch Box",
      desc: "1 Medium Cheese Stuffed Crust pizza + 1 Medium Beef & Cheddar Stuffed Crust pizza + Potato wedges + Salad + Pepsi 1L.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/deals-pp_03.jpg",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/deal-03.jpg",
      price: 245,
    },
    {
      id: "deal05",
      name: "Ranch Box",
      desc: "1 Medium Cheese Stuffed Crust pizza + 1 Medium Beef & Cheddar Stuffed Crust pizza + Potato wedges + Salad + Pepsi 1L.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/deals-pp_02.jpg",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/deal-02.jpg",
      price: 240,
    },
    {
      id: "deal06",
      name: "Ranch Box",
      desc: "1 Medium Cheese Stuffed Crust pizza + 1 Medium Beef & Cheddar Stuffed Crust pizza + Potato wedges + Salad + Pepsi 1L.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/deals-pp_01.jpg",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/deal-01.jpg",
      price: 323,
    },
    {
      id: "deal07",
      name: "Ranch Box",
      desc: "1 Medium Cheese Stuffed Crust pizza + 1 Medium Beef & Cheddar Stuffed Crust pizza + Potato wedges + Salad + Pepsi 1L.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/deals-pp_01.jpg",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/deal-01.jpg",
      price: 245,
    },
    {
      id: "deal08",
      name: "Ranch Box",
      desc: "1 Medium Cheese Stuffed Crust pizza + 1 Medium Beef & Cheddar Stuffed Crust pizza + Potato wedges + Salad + Pepsi 1L.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/deals-pp_02.jpg",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/deal-02.jpg",
      price: 240,
    },
    {
      id: "deal09",
      name: "Ranch Box",
      desc: "1 Medium Cheese Stuffed Crust pizza + 1 Medium Beef & Cheddar Stuffed Crust pizza + Potato wedges + Salad + Pepsi 1L.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/deals-pp_03.jpg",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/deal-03.jpg",
      price: 323,
    },
    {
      id: "deal010",
      name: "Ranch Box",
      desc: "1 Medium Cheese Stuffed Crust pizza + 1 Medium Beef & Cheddar Stuffed Crust pizza + Potato wedges + Salad + Pepsi 1L.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/deals-pp_03.jpg",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/deal-03.jpg",
      price: 245,
    },
    {
      id: "deal011",
      name: "Ranch Box",
      desc: "1 Medium Cheese Stuffed Crust pizza + 1 Medium Beef & Cheddar Stuffed Crust pizza + Potato wedges + Salad + Pepsi 1L.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/deals-pp_02.jpg",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/deal-02.jpg",
      price: 240,
    },
    {
      id: "deal012",
      name: "Ranch Box",
      desc: "1 Medium Cheese Stuffed Crust pizza + 1 Medium Beef & Cheddar Stuffed Crust pizza + Potato wedges + Salad + Pepsi 1L.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/deals-pp_01.jpg",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/deal-01.jpg",
      price: 323,
    },
  ],
  pizza: [
    {
      id: "pizza01",
      name: "BBQ Chicken Ranch",
      desc: "Ranch base sauce with grilled chicken pieces, topped with mushroom slices, onions, mixed with Mozzarella and topped with tasty BBQ sauce and chopped parsley.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pizza-pp_01.png",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pizza-01.jpg",
      price: [85, 111, 129],
    },
    {
      id: "pizza02",
      name: "Dynamite Chicken Ranch",
      desc: "Ranch base sauce with grilled chicken pieces, mushroom slices, mozzarella cheese, diced tomatoes and crushed garlic. Finished off with delicious drizzle of Dynamite Sauce and chopped parsley.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pizza-pp_02.png",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pizza-02.jpg",
      price: [85, 111, 129],
    },
    {
      id: "pizza03",
      name: "Margherita",
      desc: "Ranch base sauce with grilled chicken pieces, mushroom slices, mozzarella cheese, diced tomatoes and crushed garlic. Finished off with delicious drizzle of Dynamite Sauce and chopped parsley.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pizza-pp_03.png",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pizza-03.jpg",
      price: [85, 111, 129],
    },
    {
      id: "pizza04",
      name: "Super Supreme",
      desc: "Ranch base sauce with grilled chicken pieces, mushroom slices, mozzarella cheese, diced tomatoes and crushed garlic. Finished off with delicious drizzle of Dynamite Sauce and chopped parsley.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pizza-pp_04.png",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pizza-04.jpg",
      price: [85, 111, 129],
    },
    {
      id: "pizza05",
      name: "Vegetarian",
      desc: "Ranch base sauce with grilled chicken pieces, mushroom slices, mozzarella cheese, diced tomatoes and crushed garlic. Finished off with delicious drizzle of Dynamite Sauce and chopped parsley.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pizza-pp_05.png",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pizza-05.jpg",
      price: [85, 111, 129],
    },
    {
      id: "pizza06",
      name: "Spicy Chicken Ranch",
      desc: "Ranch base sauce with grilled chicken pieces, mushroom slices, mozzarella cheese, diced tomatoes and crushed garlic. Finished off with delicious drizzle of Dynamite Sauce and chopped parsley.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pizza-pp_06.png",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pizza-06.jpg",
      price: [85, 111, 129],
    },
    {
      id: "pizza07",
      name: "Prawn",
      desc: "Ranch base sauce with grilled chicken pieces, mushroom slices, mozzarella cheese, diced tomatoes and crushed garlic. Finished off with delicious drizzle of Dynamite Sauce and chopped parsley.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pizza-pp_07.png",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pizza-07.jpg",
      price: [85, 111, 129],
    },
    {
      id: "pizza08",
      name: "Hut Savers Stuffed Crust Offer",
      desc: "Ranch base sauce with grilled chicken pieces, topped with mushroom slices, onions, mixed with Mozzarella and topped with tasty BBQ sauce and chopped parsley.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pizza-pp_08.png",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pizza-08.jpg",
      price: [85, 111, 129],
    },
    {
      id: "pizza09",
      name: "Hut Savers Stuffed Crust Offer",
      desc: "Ranch base sauce with grilled chicken pieces, topped with mushroom slices, onions, mixed with Mozzarella and topped with tasty BBQ sauce and chopped parsley.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pizza-pp_09.png",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pizza-09.jpg",
      price: [85, 111, 129],
    },
    {
      id: "pizza010",
      name: "Hut Savers Stuffed Crust Offer",
      desc: "Ranch base sauce with grilled chicken pieces, topped with mushroom slices, onions, mixed with Mozzarella and topped with tasty BBQ sauce and chopped parsley.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pizza-pp_010.png",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pizza-10.jpg",
      price: [85, 111, 129],
    },
    {
      id: "pizza011",
      name: "Hut Savers Stuffed Crust Offer",
      desc: "Ranch base sauce with grilled chicken pieces, topped with mushroom slices, onions, mixed with Mozzarella and topped with tasty BBQ sauce and chopped parsley.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pizza-pp_011.png",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pizza-11.jpg",
      price: [85, 111, 129],
    },
    {
      id: "pizza012",
      name: "Hut Savers Stuffed Crust Offer",
      desc: "Ranch base sauce with grilled chicken pieces, topped with mushroom slices, onions, mixed with Mozzarella and topped with tasty BBQ sauce and chopped parsley.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pizza-pp_012.png",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pizza-12.jpg",
      price: [85, 111, 129],
    },
    {
      id: "pizza013",
      name: "Hut Savers Stuffed Crust Offer",
      desc: "Ranch base sauce with grilled chicken pieces, topped with mushroom slices, onions, mixed with Mozzarella and topped with tasty BBQ sauce and chopped parsley.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pizza-pp_013.png",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pizza-13.jpg",
      price: [85, 111, 129],
    },
    {
      id: "pizza014",
      name: "Hut Savers Stuffed Crust Offer",
      desc: "Ranch base sauce with grilled chicken pieces, topped with mushroom slices, onions, mixed with Mozzarella and topped with tasty BBQ sauce and chopped parsley.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pizza-pp_014.png",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pizza-14.jpg",
      price: [85, 111, 129],
    },
    {
      id: "pizza015",
      name: "Hut Savers Stuffed Crust Offer",
      desc: "Ranch base sauce with grilled chicken pieces, topped with mushroom slices, onions, mixed with Mozzarella and topped with tasty BBQ sauce and chopped parsley.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pizza-pp_015.png",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pizza-15.jpg",
      price: [85, 111, 129],
    },
    {
      id: "pizza016",
      name: "Hut Savers Stuffed Crust Offer",
      desc: "Ranch base sauce with grilled chicken pieces, topped with mushroom slices, onions, mixed with Mozzarella and topped with tasty BBQ sauce and chopped parsley.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pizza-pp_016.png",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pizza-16.jpg",
      price: [85, 111, 129],
    },
    {
      id: "pizza017",
      name: "Hut Savers Stuffed Crust Offer",
      desc: "Ranch base sauce with grilled chicken pieces, topped with mushroom slices, onions, mixed with Mozzarella and topped with tasty BBQ sauce and chopped parsley.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pizza-pp_017.png",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pizza-17.jpg",
      price: [85, 111, 129],
    },
  ],
  pasta: [
    {
      id: "pasta01",
      name: "spaghetti noodles",
      desc: "Fresh gorgeous Egyptian sun-dried tomato 'pesto' served with a handful of chopped fresh basil and olive oil. If you’re a lover of sun dried tomatoes, this is the closest to heaven you’ll ever get.",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pasta-01.jpg",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pasta-pp_01.jpg",
      price: 103,
    },
    {
      id: "pasta02",
      name: "Spinaci alla Paradiso",
      desc: "Fresh gorgeous Egyptian sun-dried tomato 'pesto' served with a handful of chopped fresh basil and olive oil. If you’re a lover of sun dried tomatoes, this is the closest to heaven you’ll ever get.",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pasta-02.jpg",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pasta-pp_02.jpg",
      price: 103,
    },
    {
      id: "pasta03",
      name: "Basil Penne all'Arrabbiata",
      desc: "Fresh gorgeous Egyptian sun-dried tomato 'pesto' served with a handful of chopped fresh basil and olive oil. If you’re a lover of sun dried tomatoes, this is the closest to heaven you’ll ever get.",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pasta-03.jpg",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pasta-pp_03.jpg",
      price: 103,
    },
    {
      id: "pasta04",
      name: "Phanthai",
      desc: "Fresh gorgeous Egyptian sun-dried tomato 'pesto' served with a handful of chopped fresh basil and olive oil. If you’re a lover of sun dried tomatoes, this is the closest to heaven you’ll ever get.",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pasta-04.jpg",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pasta-pp_04.jpg",
      price: 103,
    },
    {
      id: "pasta04",
      name: "Phanthai",
      desc: "Fresh gorgeous Egyptian sun-dried tomato 'pesto' served with a handful of chopped fresh basil and olive oil. If you’re a lover of sun dried tomatoes, this is the closest to heaven you’ll ever get.",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pasta-04.jpg",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pasta-pp_04.jpg",
      price: 103,
    },
    {
      id: "pasta03",
      name: "Basil Penne all'Arrabbiata",
      desc: "Fresh gorgeous Egyptian sun-dried tomato 'pesto' served with a handful of chopped fresh basil and olive oil. If you’re a lover of sun dried tomatoes, this is the closest to heaven you’ll ever get.",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pasta-03.jpg",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pasta-pp_03.jpg",
      price: 103,
    },
    {
      id: "pasta02",
      name: "Spinaci alla Paradiso",
      desc: "Fresh gorgeous Egyptian sun-dried tomato 'pesto' served with a handful of chopped fresh basil and olive oil. If you’re a lover of sun dried tomatoes, this is the closest to heaven you’ll ever get.",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pasta-02.jpg",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pasta-pp_02.jpg",
      price: 103,
    },
    {
      id: "pasta01",
      name: "spaghetti noodles",
      desc: "Fresh gorgeous Egyptian sun-dried tomato 'pesto' served with a handful of chopped fresh basil and olive oil. If you’re a lover of sun dried tomatoes, this is the closest to heaven you’ll ever get.",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pasta-01.jpg",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pasta-pp_01.jpg",
      price: 103,
    },
    {
      id: "pasta01",
      name: "spaghetti noodles",
      desc: "Fresh gorgeous Egyptian sun-dried tomato 'pesto' served with a handful of chopped fresh basil and olive oil. If you’re a lover of sun dried tomatoes, this is the closest to heaven you’ll ever get.",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pasta-01.jpg",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pasta-pp_01.jpg",
      price: 103,
    },
    {
      id: "pasta02",
      name: "Spinaci alla Paradiso",
      desc: "Fresh gorgeous Egyptian sun-dried tomato 'pesto' served with a handful of chopped fresh basil and olive oil. If you’re a lover of sun dried tomatoes, this is the closest to heaven you’ll ever get.",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pasta-02.jpg",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pasta-pp_02.jpg",
      price: 103,
    },
    {
      id: "pasta03",
      name: "Basil Penne all'Arrabbiata",
      desc: "Fresh gorgeous Egyptian sun-dried tomato 'pesto' served with a handful of chopped fresh basil and olive oil. If you’re a lover of sun dried tomatoes, this is the closest to heaven you’ll ever get.",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pasta-03.jpg",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pasta-pp_03.jpg",
      price: 103,
    },
    {
      id: "pasta04",
      name: "Phanthai",
      desc: "Fresh gorgeous Egyptian sun-dried tomato 'pesto' served with a handful of chopped fresh basil and olive oil. If you’re a lover of sun dried tomatoes, this is the closest to heaven you’ll ever get.",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pasta-04.jpg",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pasta-pp_04.jpg",
      price: 103,
    },
    {
      id: "pasta04",
      name: "Phanthai",
      desc: "Fresh gorgeous Egyptian sun-dried tomato 'pesto' served with a handful of chopped fresh basil and olive oil. If you’re a lover of sun dried tomatoes, this is the closest to heaven you’ll ever get.",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pasta-04.jpg",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pasta-pp_04.jpg",
      price: 103,
    },
    {
      id: "pasta03",
      name: "Basil Penne all'Arrabbiata",
      desc: "Fresh gorgeous Egyptian sun-dried tomato 'pesto' served with a handful of chopped fresh basil and olive oil. If you’re a lover of sun dried tomatoes, this is the closest to heaven you’ll ever get.",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pasta-03.jpg",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pasta-pp_03.jpg",
      price: 103,
    },
    {
      id: "pasta02",
      name: "Spinaci alla Paradiso",
      desc: "Fresh gorgeous Egyptian sun-dried tomato 'pesto' served with a handful of chopped fresh basil and olive oil. If you’re a lover of sun dried tomatoes, this is the closest to heaven you’ll ever get.",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pasta-02.jpg",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pasta-pp_02.jpg",
      price: 103,
    },
    {
      id: "pasta01",
      name: "spaghetti noodles",
      desc: "Fresh gorgeous Egyptian sun-dried tomato 'pesto' served with a handful of chopped fresh basil and olive oil. If you’re a lover of sun dried tomatoes, this is the closest to heaven you’ll ever get.",
      cardImageUrl: "https://islamabdelsalam.com/rosto/images/pasta-01.jpg",
      imageUrl: "https://islamabdelsalam.com/rosto/images/pasta-pp_01.jpg",
      price: 103,
    },
  ],
  starters: [
    {
      id: "starter-01",
      name: "Spicy Kriss Cut Fries",
      desc: "Oven baked kriss cut fries with Tabasco sprinkles.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/starter-01.jpg",
      price: 35,
    },
    {
      id: "starter-02",
      name: "Fire Wings",
      desc: "Served with our special BBQ sauce (Spicy Hot).",
      imageUrl: "https://islamabdelsalam.com/rosto/images/starter-02.jpg",
      price: 70,
    },
    {
      id: "starter-03",
      name: "Potato Wedges",
      desc: "Crispy,oven baked Potato wedges. Crispy,oven baked Potato wedges.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/starter-03.jpg",
      price: 45,
    },
    {
      id: "starter-04",
      name: "Garlic Bread Supreme",
      desc: "Freshly baked French Bread with Garlic butter,melted mozzare..",
      imageUrl: "https://islamabdelsalam.com/rosto/images/starter-04.jpg",
      price: 25,
    },
    {
      id: "starter-05",
      name: "Chicken BBQ Spin Rolls",
      desc: "Tortilla Rolls Stuffed with BBQ Chicken.",
      imageUrl: "https://islamabdelsalam.com/rosto/images/starter-05.jpg",
      price: 55,
    },
    {
      id: "starter-06",
      name: "Chicken Tenders",
      desc: "Delicious bite sized Chicken coated in a crispy breading,served with..",
      imageUrl: "https://islamabdelsalam.com/rosto/images/starter-06.jpg",
      price: 95,
    },
  ],
  salads: [
    {
      id: "salad-01",
      name: "Coleslaw",
      imageUrl: "https://islamabdelsalam.com/rosto/images/salad-01.jpg",
      price: 35,
    },
    {
      id: "salad-02",
      name: "Green Salad",
      imageUrl: "https://islamabdelsalam.com/rosto/images/salad-02.jpg",
      price: 35,
    },
    {
      id: "salad-03",
      name: "Garlic Sauce",
      imageUrl: "https://islamabdelsalam.com/rosto/images/salad-03.jpg",
      price: 35,
    },
    {
      id: "salad-04",
      name: "Vegetable with Mayonnaise",
      imageUrl: "https://islamabdelsalam.com/rosto/images/salad-04.jpg",
      price: 35,
    },
    {
      id: "salad-05",
      name: "Potato with Mayonnaise",
      imageUrl: "https://islamabdelsalam.com/rosto/images/salad-05.jpg",
      price: 35,
    },
    {
      id: "salad-06",
      name: "White Cheese",
      imageUrl: "https://islamabdelsalam.com/rosto/images/salad-06.jpg",
      price: 35,
    },
  ],
  desserts: [
    {
      id: "dessert-01",
      name: "Chocolate & Marshmallow",
      imageUrl: "https://islamabdelsalam.com/rosto/images/dessert-01.jpg",
      price: 35,
    },
    {
      id: "dessert-02",
      name: "Chocolate Cake",
      imageUrl: "https://islamabdelsalam.com/rosto/images/dessert-02.jpg",
      price: 35,
    },
    {
      id: "dessert-03",
      name: "Cheese Cake",
      imageUrl: "https://islamabdelsalam.com/rosto/images/dessert-03.jpg",
      price: 35,
    },
  ],
  drinks: [
    {
      id: "drink-01",
      name: "7 Up",
      imageUrl: "https://islamabdelsalam.com/rosto/images/drink-01.jpg",
      price: 35,
    },
    {
      id: "drink-02",
      name: "Pepsi",
      imageUrl: "https://islamabdelsalam.com/rosto/images/drink-02.jpg",
      price: 35,
    },
    {
      id: "drink-03",
      name: "Mirinda",
      imageUrl: "https://islamabdelsalam.com/rosto/images/drink-03.jpg",
      price: 35,
    },
    {
      id: "drink-04",
      name: "Diet Pepsi",
      imageUrl: "https://islamabdelsalam.com/rosto/images/drink-04.jpg",
      price: 35,
    },
  ],
};

export default data;
