const data = [
  {
    id: "pizza01",
    category: "Pizza",
    name: "Hut Savers Stuffed Crust Offer",
    desc: "Ranch base sauce with grilled chicken pieces, topped with mushroom slices, onions, mixed with Mozzarella and topped with tasty BBQ sauce and chopped parsley.",
    imageUrl: "/../public/images/pizza-pp_01.png",
    price: [85, 111, 129],
  },
  {
    id: "pizza02",
    category: "Pizza",
    name: "Hut Savers Stuffed Crust Offer",
    desc: "Ranch base sauce with grilled chicken pieces, topped with mushroom slices, onions, mixed with Mozzarella and topped with tasty BBQ sauce and chopped parsley.",
    imageUrl: "/../public/images/pizza-pp_02.png",
    price: [85, 111, 129],
  },
  {
    id: "pizza03",
    category: "Pizza",
    name: "Hut Savers Stuffed Crust Offer",
    desc: "Ranch base sauce with grilled chicken pieces, topped with mushroom slices, onions, mixed with Mozzarella and topped with tasty BBQ sauce and chopped parsley.",
    imageUrl: "/../public/images/pizza-pp_03.png",
    price: [85, 111, 129],
  },
  {
    id: "pizza04",
    category: "Pizza",
    name: "Hut Savers Stuffed Crust Offer",
    desc: "Ranch base sauce with grilled chicken pieces, topped with mushroom slices, onions, mixed with Mozzarella and topped with tasty BBQ sauce and chopped parsley.",
    imageUrl: "/../public/images/pizza-pp_04.png",
    price: [85, 111, 129],
  },
  {
    id: "pizza05",
    category: "Pizza",
    name: "Hut Savers Stuffed Crust Offer",
    desc: "Ranch base sauce with grilled chicken pieces, topped with mushroom slices, onions, mixed with Mozzarella and topped with tasty BBQ sauce and chopped parsley.",
    imageUrl: "/../public/images/pizza-pp_05.png",
    price: [85, 111, 129],
  },
  {
    id: "pizza06",
    category: "Pizza",
    name: "Hut Savers Stuffed Crust Offer",
    desc: "Ranch base sauce with grilled chicken pieces, topped with mushroom slices, onions, mixed with Mozzarella and topped with tasty BBQ sauce and chopped parsley.",
    imageUrl: "/../public/images/pizza-pp_06.png",
    price: [85, 111, 129],
  },
  {
    id: "pizza07",
    category: "Pizza",
    name: "Hut Savers Stuffed Crust Offer",
    desc: "Ranch base sauce with grilled chicken pieces, topped with mushroom slices, onions, mixed with Mozzarella and topped with tasty BBQ sauce and chopped parsley.",
    imageUrl: "/../public/images/pizza-pp_07.png",
    price: [85, 111, 129],
  },
  {
    id: "pizza08",
    category: "Pizza",
    name: "Hut Savers Stuffed Crust Offer",
    desc: "Ranch base sauce with grilled chicken pieces, topped with mushroom slices, onions, mixed with Mozzarella and topped with tasty BBQ sauce and chopped parsley.",
    imageUrl: "/../public/images/pizza-pp_08.png",
    price: [85, 111, 129],
  },
  {
    id: "pizza09",
    category: "Pizza",
    name: "Hut Savers Stuffed Crust Offer",
    desc: "Ranch base sauce with grilled chicken pieces, topped with mushroom slices, onions, mixed with Mozzarella and topped with tasty BBQ sauce and chopped parsley.",
    imageUrl: "/../public/images/pizza-pp_09.png",
    price: [85, 111, 129],
  },
  {
    id: "pizza010",
    category: "Pizza",
    name: "Hut Savers Stuffed Crust Offer",
    desc: "Ranch base sauce with grilled chicken pieces, topped with mushroom slices, onions, mixed with Mozzarella and topped with tasty BBQ sauce and chopped parsley.",
    imageUrl: "/../public/images/pizza-pp_010.png",
    price: [85, 111, 129],
  },
  {
    id: "pizza011",
    category: "Pizza",
    name: "Hut Savers Stuffed Crust Offer",
    desc: "Ranch base sauce with grilled chicken pieces, topped with mushroom slices, onions, mixed with Mozzarella and topped with tasty BBQ sauce and chopped parsley.",
    imageUrl: "/../public/images/pizza-pp_011.png",
    price: [85, 111, 129],
  },
  {
    id: "pizza012",
    category: "Pizza",
    name: "Hut Savers Stuffed Crust Offer",
    desc: "Ranch base sauce with grilled chicken pieces, topped with mushroom slices, onions, mixed with Mozzarella and topped with tasty BBQ sauce and chopped parsley.",
    imageUrl: "/../public/images/pizza-pp_012.png",
    price: [85, 111, 129],
  },
  {
    id: "pizza013",
    category: "Pizza",
    name: "Hut Savers Stuffed Crust Offer",
    desc: "Ranch base sauce with grilled chicken pieces, topped with mushroom slices, onions, mixed with Mozzarella and topped with tasty BBQ sauce and chopped parsley.",
    imageUrl: "/../public/images/pizza-pp_013.png",
    price: [85, 111, 129],
  },
  {
    id: "pizza014",
    category: "Pizza",
    name: "Hut Savers Stuffed Crust Offer",
    desc: "Ranch base sauce with grilled chicken pieces, topped with mushroom slices, onions, mixed with Mozzarella and topped with tasty BBQ sauce and chopped parsley.",
    imageUrl: "/../public/images/pizza-pp_014.png",
    price: [85, 111, 129],
  },
  {
    id: "pizza015",
    category: "Pizza",
    name: "Hut Savers Stuffed Crust Offer",
    desc: "Ranch base sauce with grilled chicken pieces, topped with mushroom slices, onions, mixed with Mozzarella and topped with tasty BBQ sauce and chopped parsley.",
    imageUrl: "/../public/images/pizza-pp_015.png",
    price: [85, 111, 129],
  },
  {
    id: "pizza016",
    category: "Pizza",
    name: "Hut Savers Stuffed Crust Offer",
    desc: "Ranch base sauce with grilled chicken pieces, topped with mushroom slices, onions, mixed with Mozzarella and topped with tasty BBQ sauce and chopped parsley.",
    imageUrl: "/../public/images/pizza-pp_016.png",
    price: [85, 111, 129],
  },
  {
    id: "pizza017",
    category: "Pizza",
    name: "Hut Savers Stuffed Crust Offer",
    desc: "Ranch base sauce with grilled chicken pieces, topped with mushroom slices, onions, mixed with Mozzarella and topped with tasty BBQ sauce and chopped parsley.",
    imageUrl: "/../public/images/pizza-pp_017.png",
    price: [85, 111, 129],
  },
];

export default data;
